import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Play On Exhibition',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <script src="https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"></script>
        {children}
      </body>
    </html>
  )
}
