export const playerDetails = {
    'players': [
      {
          "id": 1,
          "firstName": "Lydia",
          "lastName": "Williams",
          "prevSlide": 5,
          "currentSlide":1,
          "nextSlide":2,
          "onField": "Lydia On Field",
          "onField2": "Lydia On Field Sentance 2",
          "offField": "Lydia Off Field",
          "returnSlide":1,
        },

      {
        "id": 2,
        "firstName": "Ellie",
        "lastName": "Carpenter",
        "prevSlide": 1,
        "currentSlide":2,
        "nextSlide":3,
        "onField": "Ellie On Field",
        "onField2": "Ellie On Field Sentance 2",
        "offField": "Ellie Off Field",
        "returnSlide":2,
      },

    {
          "id": 3,
          "firstName": "Sam",
          "lastName": "Kerr",
          "prevSlide": 2,
          "currentSlide":3,
          "nextSlide":4,
          "onField": "Sam On Field",
          "onField2": "Sam On Field Sentance 2",
          "offField": "Sam Off Field",
          "returnSlide":3,
        },
  
      {
          "id": 4,
          "firstName": "Michelle",
          "lastName": "Heyman",
          "prevSlide": 3,
          "currentSlide":4,
          "nextSlide":5,
          "onField": "Michelle On Field",
          "onField2": "Michelle On Field Sentance 2",
          "offField": "Michelle Off Field",
          "returnSlide":4,
        },

      {
          "id": 5,
          "firstName": "Hayley",
          "lastName": "Raso",
          "prevSlide": 4,
          "currentSlide":5,
          "nextSlide":1,
          "onField": "Hayley On Field",
          "onField2": "Hayley On Field Sentance 2",
          "offField": "Hayley Off Field",
          "returnSlide":5,
        },
]}
