export const playerDetails = {
  'players': [
      {
          "id": 1,
          "firstName": "Nicole & Ash",
          "lastName": "Sykes",
          "position": "Defender & Striker",
          "jersey": "Retired",
          "club": "Canberra United FC",
          "retired": false,
          "imageName": "AshNicoleSykes",
          "prevSlide": "Slide5",
          "currentSlide":1,
          "nextSlide":"Slide2",
          "leftButton":"Nicole Sykes",
          "rightButton":"Ash Sykes",
          "leftText": "Nicole joined Canberra United whilst still finishing school for the league's inaugural season in 2008–09, Nicole was known as a hardworking defender who excelled on the left side and was an integral part of the United team which won the 2011-12 and became Captain in the 2013-14 W-League season, following in the footsteps of Ellie Brush and Matildas goal-keeper Lydia Williams, leading the team to another title in 2014-15.",
          "leftText2": "Nicole is currently playing for and coaching Canberra Olympic in the Capital FootballL, Women’s National Premier League. The side won the competitions Grand Final in 2022 and is currently well positioned on the table for another deep run in 2023.",
          "rightText": "Ash joined Canberra United whilst still finishing school for the league's inaugural season in 2008–09. Ash made her debut in Canberra's first match and represented Australia 19 times, with the Matildas and the Young Matildas.",
          "rightText2": "She was awarded Goal of the Year in 2013/14, the Julie Dolan Medal for Best player in the W-League for 2014-15 and was voted the Player of the Grand Final as United secured the 2014-15 title. Ash will be joining the Optus Sport broadcast team to provide expert coverage of the FIFA Women’s World Cup 2023.",
          "returnSlide":1,
          "name1": true,
          "name2": false,
          "name3": false,
          "name4": false,
          "name5": false,
        },

      {
        "id": 2,
        "firstName": "Lydia",
        "lastName": "Williams",
        "imageName": "LydiaWilliams",
        "position": "Goalkeeper",
        "jersey": "#1",
        "club": "Brighton & Hove Albion",
        "retired": false,
        "prevSlide": "Slide1",
        "currentSlide":2,
        "nextSlide":"Slide3",
        "leftButton":"Grassroots",
        "rightButton":"Glory",
        "leftText": "Lydia Williams is a proud Noongar woman from Katanning, WA. Growing up, Lydia had the opportunity to live off the land and strengthen her connection to her culture as a First Nations woman.",
        "leftText2": "At 12, moving to Canberra was a shock for Lydia. Life there was the opposite of what she knew in WA. She tried AFL and basketball but couldn't find a team or was considered too short. Finally, she found the Tuggeranong Rosellas and took up goalkeeping, which came naturally to her.",
        "rightText": "Lydia transitioned from the Australian Institute of Sport and into the senior national team at age 15. Since, she has been representing Australia in major tournaments including the 2016 and 2020 Olympic Games, the 2006, 2008, 2010, 2014, 2018 and the 2022 AFC Women’s Asian Cup.",
        "rightText2": "Lydia has represented the Matilda's in four FIFA World Cup tournaments in 2007, 2011, 2015 and 2019 and is currently preparing for her fifth and final World Cup campaign. Her first match will be against Ireland on Gadigal land in Sydney on 20 July 2023.",
        "returnSlide":2,
        "name1": false,
        "name2": true,
        "name3": false,
        "name4": false,
        "name5": false,
      },

      {  
        "id": 3,
        "firstName": "Caitlin",
        "lastName": "Munoz",
        "position": "Striker",
        "jersey": "#6",
        "club": "Canberra United FC",
        "retired": true,
        "imageName": "CaitlinMunoz",
        "prevSlide": "Slide2",
        "currentSlide":3,
        "nextSlide":"Slide4",
        "leftButton":"Grassroots",
        "rightButton":"Glory",
        "leftText": "Caitlin Munoz has had a notable career playing for various teams in Australian women's football. She is known for her contributions to women’s football in Canberra. Caitlin started her journey with Canberra Eclipse, playing in the Women's National Soccer League. She later played for Canberra United in the A-League Women competition.",
        "leftText2": "Caitlin has also played a significant role in the success of Belconnen United, contributing significantly to the club's achievements. Her character often shines during gameplay, not only in her playing ability but also in her acts of selflessness and sportsmanship.",
        "rightText": "During her A-League Women debut, she faced off against Cheryl Salisbury, a legendary Matildas player. Despite a rough tackle from Salisbury, Munoz showed her tenacity and continued to play, eventually earning a spot in the Matildas team alongside Salisbury and other notable players who made history.",
        "rightText2": "In 2007, the Matildas secured a 4-1 victory over Ghana in the FIFA Women’s World Cup, this was the first time the Matilda's secured a victory in a World Cup. In 2019, Caitlin had decided it was time to retire, but not before one more victory. In the 2019 NPL Women's League Grand Final, she scored the winning goal for Canberra United, and left the field in celebration with her team.",
        "returnSlide":3,
        "name1": false,
        "name2": false,
        "name3": true,
        "name4": false,
        "name5": false,
        },
  
        {
          "id": 4,
          "firstName": "Michelle",
          "lastName": "Heyman",
          "position": "Striker",
          "jersey": "#23",
          "club": "Canberra United FC",
          "retired": false,
          "imageName": "MichelleHeyman",
          "prevSlide": "Slide3",
          "currentSlide":4,
          "nextSlide":"Slide5",
          "leftButton":"Grassroots",
          "rightButton":"Glory",
          "leftText": "Michelle Heyman is a player and commentator currently representing Canberra United FC in Australia’s A-League Women competition. Michelle’s journey in soccer began when she was 11, playing for the Warilla Wanderers. She later went on to play for Port Kembla and Shellharbour City before joining the Illawarra Stingrays in the NSW Women's Super League. Between W-League seasons, she has frequently returned to play for the Stingrays.",
          "leftText2": "Michelle has previously showcased her skills for W-League teams such as the Central Coast Mariners, Sydney FC, and Adelaide United. She has also played internationally for Brøndby IF in Denmark’s 2012 season, and for Western New York Flash in the United States’ 2015 National Women's Soccer League.",
          "rightText": "Michelle has represented Australia since 2010, donning the national team jersey in prestigious tournaments including the 2014 AFC Women's Asian Cup, the 2015 FIFA Women's World Cup, and the 2016 Summer Olympics. After a successful international career with the Matilda's, she announced her retirement from international football in 2019.",
          "rightText2": "Michelle’s impressive performances and goal-scoring prowess are historical, she was the 2009 A-League Women Golden Boot winner, the same year she was named the Player of the Year. In 2011-2012, she was the leagues top goal-scorer and contributed heavily to Canberra United's championship run that year. In 2021, she became the A-League Women all-time leading goal scorer, claiming a total of 73 goals.",
          "returnSlide":4,
          "name1": false,
          "name2": false,
          "name3": false,
          "name4": true,
          "name5": false,
        },

        {
          "id": 5,
          "firstName": "Ellie",
          "lastName": "Brush",
          "position": "Defender",
          "jersey": "#7",
          "club": "Canberra United",
          "retired": true,
          "imageName": "EllieBrush",
          "prevSlide": "Slide4",
          "currentSlide":5,
          "nextSlide":"Slide1",
          "leftButton":"Club Career",
          "leftText": "Ellie Brush began her football journey in 1993, playing for Weston Molongolo FC. Since then, she has played for Canberra United, Avaldsnes IL, Houston Dash, Western Sydney Wanderers, and Sydney FC.",
          "leftText2": "She received a call-up to the Matildas in 2009 and made an international debut in a friendly match against Italy. She made her second cap with the Matildas in 2012 in an international friendly match against New Zealand.",
          "rightButton":"Leadership",
          "rightText": "Brush's journey with Canberra United began in the team's inaugural season in 2008 when she was appointed captain and led the squad to the final. She later shared the captaincy with Lydia Williams in the 2009 season before assuming sole leadership, guiding the team to success in subsequent campaigns.",
          "rightText2": "Under her captaincy, Canberra United secured the A-League Women, then known as the W-League, premiership in 2011.",
          "returnSlide":5,
          "name1": false,
          "name2": false,
          "name3": false,
          "name4": false,
          "name5": true,
        },
]}
